print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
a = dap.add_item("test", "Item")
print("bbb ->" + a)
dap.add_bool("test", "bool", true)
print(dap.get_bool("test", "bool"))
print("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
