print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ")
a = dap.add_item("test", "Item")
a = dap.get_bool("test1", "bool", false)
print("bbb -> " .. tostring(a))
dap.add_bool("test", "bool", true)
print(dap.get_bool("test", "bool", false))
print("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
